[package]
name = "message-io"
version = "0.4.3"
authors = ["lemunozm <lemunozm@gmail.com>"]
edition = "2018"
readme = "README.md"
license = "Apache-2.0"
description = "Easy asynchronous network message library"
homepage = "https://github.com/lemunozm/message-io/"
repository = "https://github.com/lemunozm/message-io/"
keywords = ["network", "message", "asynchronous", "events"]
categories = ["asynchronous", "game-development", "network-programming"]
maintenance = "actively-developed"

[dependencies]
mio = { version = "0.7", features = ["os-poll", "tcp", "udp"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.1"
crossbeam-channel = "0.4.2"
log = "0.4"
net2 = "0.2.34"
